//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkPrj1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparis
    {
        public int SiparisNo { get; set; }
        public System.DateTime Tarih { get; set; }
        public int MusteriId { get; set; }
        public int UrunId { get; set; }
        public int Adet { get; set; }
    
        public virtual Musteri Musteri { get; set; }
        public virtual Urun Urun { get; set; }
    }
}
