//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkPrj1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteri
    {
        public Musteri()
        {
            this.Siparis = new HashSet<Siparis>();
        }
    
        public int MusteriId { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Sehir { get; set; }
    
        public virtual ICollection<Siparis> Siparis { get; set; }
    }
}
