//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkPrj1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urun
    {
        public Urun()
        {
            this.Siparis = new HashSet<Siparis>();
        }
    
        public int UrunId { get; set; }
        public string Adi { get; set; }
        public int Fiyati { get; set; }
    
        public virtual ICollection<Siparis> Siparis { get; set; }
    }
}
